---
title: "Questões"
format: html
---

Sobre os casos clínicos
Adaptada da PRM 2019 - FMUSP)

Mulher de 65 anos refere dor epigástrica constante irradiada para o dorso associada à anorexia, náuseas e vômitos esporádicos há 5 dias. É internada devido à amilasemia de 320 UI/dL (VR:20-160), bilirrubinemia normal e APACHE II de 8 pontos (mortalidade 8% não cirúrgico e 3% pós-cirúrgico). A ultrassonografia de abdome mostrou colelitíase sem dilatação das vias biliares e com aumento das dimensões do pâncreas. Foi iniciado tratamento clínico com melhora após 48 horas. Antecedente pessoal: há 1 mês foi internada durante 5 dias devido à episódio de pancreatite. Na época, respondeu bem ao tratamento clínico e com boa aceitação de dieta hipogordurosa. Neste momento (atual), além da observação clínica, a conduta da terapia nutricional mais adequada é: 

(   ) Nutrição enteral

(   ) Via oral zero

(   ) Nutrição parenteral periférica

(   ) Dieta via oral hipogordurosa

Resposta correta: dieta via oral hipogordurosa. 




PRM- FMUSP - 2024 

Tema: Pancreatite crônica em paciente queimado

Resposta correta: não lembro agora.... 